package com.example.productfireapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val WhiteBG = Color(0xFFFFFFFF)
val CustomGray = Color(0xFF868889)
val DarkPrimary = Color(0xFF6CC51D)
val LightPrimary = Color(0xFFAEDC81)
val MediumPrimary = Color(0xFF6CC51D)
val LightGray = Color(0xFFDCDCDC)
val BorderColor = Color(0xFFEBEBEB)
val RedCircle = Color(0xFFF14336)
val YellowCircle = Color(0xFFFFC107)
val TextBoxGray = Color(0xFFF4F5F9)
val LightOrange = Color(0xFFFFE9E5)
val BGGray = Color(0xFFE6F2EA)
val LightYellow = Color(0xFFFFF6E3)
val GrColor = Color(0xFFF3EFFA)
val OilColor = Color(0xFFDCF4F5)
val PinkC = Color(0xFFFFE8F2)
val LightBlue = Color(0xFFD2EFFF)
val PeachColor = Color(0xFFFFCEC1)
val BrocolyColor = Color(0xFFD2FFD0)
val PomegranateColor = Color(0xFFFFE3E2)
val GrapesColor = Color(0xFFFEE1ED)
val PineapleColor = Color(0xFFFFE6C2)
val AvocadoColor = Color(0xFFFCFFD9)
val AvocadoEventTextColor = Color(0xFFE8AD41)
val Rusty1 = Color(0xFFC7463C)
val SwipeBoxColor = Color(0xFFEF574B)